### PR TITLE
Add thor gem dependency to gemspec

### PR DESCRIPTION
**Pull request by jacobat**
Thor was missing after `gem install private_gem`.

/cc @staugaard

### CODE REVIEW

**Comment by bquorning** [comment]
:+1:

**Comment by staugaard** [comment]
:+1:

**Comment by jacobat** [comment]
Tagged and pushed v1.1.1. I can't release it to Rubygems.org though.

**Comment by staugaard** [comment]
Thanks. It is now released.

On Sat, May 30, 2015 at 12:16 AM, Jacob Atzen <notifications@github.com>
wrote:

> Tagged and pushed v1.1.1. I can't release it to Rubygems.org though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/private_gem/pull/6#issuecomment-107001414>.
>



-- 
Thanks,
Mick Staugaard
Senior Principal Engineer

Zendesk <http://www.zendesk.com/>
Github: @staugaard

**Pull request merged**
